services:
    resource.point:
        parent:    "api.resource"
        arguments: [ 'AppBundle\Entity\Point' ]
        tags:      [ { name: "api.resource" } ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.point.nearest" ] ]

    resource.path:
        parent:    "api.resource"
        arguments: [ 'AppBundle\Entity\Path' ]
        calls:
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "path" ] } ]
            -      method:    "initDenormalizationContext"
                   arguments: [ { groups: [ "path" ] } ]
            -      method:    "initFilters"
                   arguments: [ [ "@resource.point.nearest" ] ]
        tags:      [ { name: "api.resource" } ]

    resource.point.nearest:
        class: 'AppBundle\Filter\SortByNearestFilter'
        arguments: [ '@doctrine' ]
