services:
    resource.point:
        parent:    "api.resource"
        arguments: [ 'AppBundle\Entity\Point' ]
        tags:      [ { name: "api.resource" } ]

    resource.path:
        parent:    "api.resource"
        arguments: [ 'AppBundle\Entity\Path' ]
        tags:      [ { name: "api.resource" } ]
